<td align="left">
  <p>
  <b>Terms of Service</b>
  </p>
  <p>
  <ol>
    <li>No unsolicited e-mails (spam) ever to be sent vai our systems at anytime.</li>
    <li>No malicious files or mail attachments such as viruses ever to be intentionally distributed vai our systems.</li>
    <li>At no time will the sender of mails vai our systems or any other use addresses generated by our services to promote Porn, Anti-Religeon, Criminal Activity, Warez or anything we feel is breaching what we feel to be legitimate content.</li>
    <li>No mail addresses should every be added to ones list unless through the voluntary subscription process the mail address owner must go through.</li>
    <li>Every mail outbound MUST contain a working REMOVAL LINK to allow the receipent the option to unsubscribe from receiving further mails in the future from any lists on our systems.</li>
    <li>List owners should not try to abuse the frequency at which they mail to their list members.</li>
    <li>You agree to light advertising Planet X Mail applies to all Lists.</li>
    <li>Addresses may not simply be tranferred from one list to another without the subscription process taking place per each address. Or the list is transfered in it's entirety.</li>
  </ol>
  </p>
  <p>
  <b>Additional notes:</b>
  </p>
  <p>
    <b>Important!</b> You may not have any spamCOP filters attached to any email addresses used to sign-up with. If you do, you voluntarily
    agree to allow www.planetxmail.com to sue you for any damages and fees that may be caused as a result of unwarrented spamming reports
    attached to www.planetxmail.com.  All sign-ups are confirmed to be valid and ONLY added to the lists if the confirmation links are
    used to confirm each sign-up.  www.planetxmail.com is dedicated to legitimate mailing to those that voluntarily sign-up their
    email address to receive mail from others on the list.  ALL mails have a <b>remove from list link at the bottom</b>.  All list data is
    secure and safe and <b>NEVER</b> released unless requested by the List Owner and ONLY sent to their registered email address.
  </p>
  <p>
  PlanetXMail reserves the right to terminate and cancel the accounts, lists and services of any individual willing to proceed in any acts forbidden per the list above.
  The offending list owners list of addresses will be concidered illegally obtained and therefor erased from our systems with no liablity on the part of PlanetXMail conforming
  to the policies it set forth.  Further action may or may not be taken to warn others of the offensive nature of the individual(s) involved in intentional
  disruption of normal operatings and compliance to terms stated here in.
  </p>
  <p>
  Planet X Mail owner,<br>
  <img src="images/signature.jpg">
  </p>
</td>